# Cargo.toml
[package]
name = "task-backend"
version = "0.1.0"
edition = "2021"

# ライブラリとしても使用できるように設定
[lib]
name = "task_backend"
path = "src/lib.rs"

[dependencies]
migration = { path = "./migration" }
axum = { version = "0.7", features = ["macros", "json"] } # Webフレームワーク
tokio = { version = "1", features = ["full"] } # 非同期ランタイム
sea-orm = { version = "1.1.11", features = [
  "runtime-tokio-rustls",
  "sqlx-postgres",
  "macros",
] } # ORM
sea-orm-migration = "1.1.11" # ORMマイグレーションツール
serde = { version = "1", features = ["derive"] } # シリアライズ/デシリアライズ
serde_json = "1" # JSONサポート
uuid = { version = "1", features = ["v4", "serde"] } # UUID生成
tracing = "0.1" # ロギング
tracing-subscriber = { version = "0.3", features = ["env-filter"] } # tracingの設定
thiserror = "1" # エラーハンドリング用
dotenvy = "0.15" # .envファイル読み込み
chrono = { version = "0.4", features = ["serde"] } # 日時操作
async-trait = "0.1" # ActiveModelBehavior の async fn のために追加
tower = "0.5" # テスト用にtowerを追加
tower-http = "0.5" # HTTP関連機能
hyper = "1.2" # HTTPクライアント

[dev-dependencies]
reqwest = { version = "0.12", features = ["json"] }
testcontainers = { version = "0.21.0", features = ["blocking"] }
testcontainers-modules = { version = "0.9.0", features = ["postgres"] }
once_cell = "1"
