# docker-compose.yml
version: "3.8"
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_db # データベース名を指定 (任意)
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # データ永続化 (任意)

volumes:
  postgres_data:
