[build]
# CPU コア数に合わせて自動で並列ジョブ数を設定する場合は 0 に
# jobs = 0
jobs = 8
# rustc のラッパーとして sccache を指定
rustc-wrapper = "sccache"

[registries.crates-io]
# クレートのダウンロード並列数
protocol = "sparse"

[profile.ci-check]
# CI用の軽量チェックプロファイル
inherits = "dev"
debug = 0
incremental = false

[env]
# 環境変数展開を使ってホーム下のキャッシュディレクトリを指定
SCCACHE_DIR = "${HOME}/.cache/sccache"
