[build]
# 並列ジョブ数の最適化（CPU数に応じて調整）
jobs = 8

[target.x86_64-unknown-linux-gnu]
# より高速なリンカーを使用
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[registries.crates-io]
# クレートのダウンロード並列数
protocol = "sparse"

[profile.ci-check]
# CI用の軽量チェックプロファイル
inherits = "dev"
debug = 0
incremental = false